name: ResusableWorkflow-Build

on:
  workflow_call:
    inputs:
      versionnode:
        description: "Version de node"
        required: true
        type: string
      app-name-zip:
        description: "Nombre de la aplicacion"
        required: true
        type: string
      app-name:
        description: "Nombre de la aplicacion"
        required: true
        type: string        
      source-path:
        description: "Carpeta de archivos del build"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setear version de node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.versionnode }}

      - name: Restore
        run: |
          npm install -g @angular/cli
          npm install

      - name: build
        run: ng build --configuration production   

      - name: Comprimir con powershell
        shell: pwsh
        run: |
          if (Test-Path ${{ inputs.app-name-zip }}) { Remove-Item ${{ inputs.app-name-zip }} -Force }
          Push-Location ${{ inputs.source-path }}
          Compress-Archive -Path * -DestinationPath $env:GITHUB_WORKSPACE/${{ inputs.app-name-zip }}
          Pop-Location
          Write-Host "Tarea finalizada"

      - name: Publicar artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app-name }}
          path: ${{ inputs.app-name-zip }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      - name: Sync S3
        run: |
          cd ${{ inputs.source-path }}
          dir
          aws s3 ls s3://amzn-s3-front-test
          aws s3 rm s3://amzn-s3-front-test --recursive
          aws sync . s3://amzn-s3-front-test
          aws s3 ls s3://amzn-s3-front-test

